[package]
name = "encrypted-tao"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.3.1", features = ["openssl"] }
pest = "2.5.6"
pest_derive = "2.5.6"
postgres = "0.19.5"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"


[[bin]]
name="tao-server"
path = "src/bin/server.rs"

[[bin]]
name="main"
path = "src/bin/main.rs"
